name: Build Docker Image for Multiple Platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (if needed)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image for multiple platforms
      - name: Build and push Docker image for multiple platforms
        run: |
          platforms="linux/amd64,linux/arm/v7,linux/arm64"
          repo_name="go-vue-build-img"  # Replace this with your repo name
          tag="1.23.4"

          docker buildx build \
            --platform $platforms \
            --file Dockerfile \
            --tag $repo_name-amd64:$tag \
            --tag $repo_name-armv7:$tag \
            --tag $repo_name-aarch64:$tag \
            --push .
